const customers = [
  {
    id: 1,
    name: "Vergil Hebblewhite",
    description: "Assistant Professor",
    email: "vhebblewhite0@com.com",
    address: "Apt 894",
    phone: "618-452-9162",
  },
  {
    id: 2,
    name: "Jeanna Lukasik",
    description: "Web Developer II",
    email: "jlukasik1@usgs.gov",
    address: "Suite 54",
    phone: "929-532-0911",
  },
  {
    id: 3,
    name: "Amos Markl",
    description: "Analyst Programmer",
    email: "amarkl2@stumbleupon.com",
    address: "7th Floor",
    phone: "974-713-3182",
  },
  {
    id: 4,
    name: "Terza Crohan",
    description: "Software Engineer IV",
    email: "tcrohan3@kickstarter.com",
    address: "PO Box 63932",
    phone: "103-172-2644",
  },
  {
    id: 5,
    name: "Osgood Cohane",
    description: "Help Desk Technician",
    email: "ocohane4@istockphoto.com",
    address: "Suite 36",
    phone: "846-881-2373",
  },
  {
    id: 6,
    name: "Kahlil Pietruszewicz",
    description: "Computer Systems Analyst III",
    email: "kpietruszewicz5@usa.gov",
    address: "Apt 331",
    phone: "634-839-8643",
  },
  {
    id: 7,
    name: "Evangelin Revett",
    description: "Recruiting Manager",
    email: "erevett6@arstechnica.com",
    address: "Suite 39",
    phone: "770-365-1857",
  },
  {
    id: 8,
    name: "Elsy Mattei",
    description: "Research Assistant I",
    email: "emattei7@gizmodo.com",
    address: "20th Floor",
    phone: "562-609-3437",
  },
  {
    id: 9,
    name: "Revkah Kneale",
    description: "Senior Developer",
    email: "rkneale8@networkadvertising.org",
    address: "PO Box 65150",
    phone: "656-210-8742",
  },
  {
    id: 10,
    name: "Thorny Lidgard",
    description: "Quality Control Specialist",
    email: "tlidgard9@seattletimes.com",
    address: "PO Box 15819",
    phone: "243-235-0430",
  },
  {
    id: 11,
    name: "Elicia Girodin",
    description: "Community Outreach Specialist",
    email: "egirodina@freewebs.com",
    address: "Suite 7",
    phone: "515-436-4073",
  },
  {
    id: 12,
    name: "Letta Keggin",
    description: "Human Resources Manager",
    email: "lkegginb@seattletimes.com",
    address: "Suite 36",
    phone: "153-150-8256",
  },
  {
    id: 13,
    name: "Marget Bletcher",
    description: "Senior Financial Analyst",
    email: "mbletcherc@oaic.gov.au",
    address: "Room 1692",
    phone: "373-331-7290",
  },
  {
    id: 14,
    name: "Meryl Gianettini",
    description: "Speech Pathologist",
    email: "mgianettinid@g.co",
    address: "Apt 1381",
    phone: "701-408-9714",
  },
  {
    id: 15,
    name: "Emilia MacLaverty",
    description: "Chemical Engineer",
    email: "emaclavertye@zimbio.com",
    address: "Room 568",
    phone: "544-682-9325",
  },
  {
    id: 16,
    name: "Phaidra Carbery",
    description: "Assistant Manager",
    email: "pcarberyf@pinterest.com",
    address: "PO Box 10183",
    phone: "503-589-2182",
  },
  {
    id: 17,
    name: "Shaine Stockhill",
    description: "VP Sales",
    email: "sstockhillg@flickr.com",
    address: "Room 1104",
    phone: "207-638-5135",
  },
  {
    id: 18,
    name: "Rodd Blythe",
    description: "Office Assistant III",
    email: "rblytheh@hostgator.com",
    address: "Room 287",
    phone: "319-755-0696",
  },
  {
    id: 19,
    name: "Saundra Kliemchen",
    description: "Research Nurse",
    email: "skliemcheni@google.es",
    address: "Apt 504",
    phone: "241-563-4352",
  },
  {
    id: 20,
    name: "Hernando Pingstone",
    description: "VP Product Management",
    email: "hpingstonej@ovh.net",
    address: "Room 672",
    phone: "150-235-2147",
  },
  {
    id: 21,
    name: "Bentlee Lightoller",
    description: "Senior Developer",
    email: "blightollerk@sourceforge.net",
    address: "Apt 165",
    phone: "806-582-6360",
  },
  {
    id: 22,
    name: "Barde Jinda",
    description: "Professor",
    email: "bjindal@nps.gov",
    address: "Suite 51",
    phone: "379-144-4748",
  },
  {
    id: 23,
    name: "Colman Bulcroft",
    description: "Graphic Designer",
    email: "cbulcroftm@blinklist.com",
    address: "Suite 29",
    phone: "295-862-3182",
  },
  {
    id: 24,
    name: "Preston MacSporran",
    description: "Information Systems Manager",
    email: "pmacsporrann@qq.com",
    address: "Suite 99",
    phone: "857-225-4371",
  },
  {
    id: 25,
    name: "Ailsun Leftridge",
    description: "Cost Accountant",
    email: "aleftridgeo@mapy.cz",
    address: "Room 1580",
    phone: "556-485-3779",
  },
  {
    id: 26,
    name: "Malcolm Metschke",
    description: "GIS Technical Architect",
    email: "mmetschkep@alibaba.com",
    address: "PO Box 22785",
    phone: "787-772-4577",
  },
  {
    id: 27,
    name: "Carlotta Wandtke",
    description: "Accountant IV",
    email: "cwandtkeq@uiuc.edu",
    address: "Room 755",
    phone: "478-162-5871",
  },
  {
    id: 28,
    name: "Darnall Sandcroft",
    description: "Teacher",
    email: "dsandcroftr@tuttocitta.it",
    address: "Apt 1191",
    phone: "746-413-2931",
  },
  {
    id: 29,
    name: "Aurie Croose",
    description: "Electrical Engineer",
    email: "acrooses@boston.com",
    address: "5th Floor",
    phone: "433-931-6074",
  },
  {
    id: 30,
    name: "Cassie Isherwood",
    description: "Legal Assistant",
    email: "cisherwoodt@storify.com",
    address: "PO Box 1154",
    phone: "381-149-7873",
  },
  {
    id: 31,
    name: "Kasey Victor",
    description: "Web Designer III",
    email: "kvictoru@chronoengine.com",
    address: "16th Floor",
    phone: "490-680-0025",
  },
  {
    id: 32,
    name: "Leonelle Nacey",
    description: "Analyst Programmer",
    email: "lnaceyv@jimdo.com",
    address: "Room 226",
    phone: "262-559-0385",
  },
  {
    id: 33,
    name: "Nathalia Moscrop",
    description: "Analyst Programmer",
    email: "nmoscropw@lulu.com",
    address: "PO Box 59727",
    phone: "586-484-6878",
  },
  {
    id: 34,
    name: "Lonnie O'Kerin",
    description: "Account Executive",
    email: "lokerinx@yellowpages.com",
    address: "Suite 90",
    phone: "246-615-5649",
  },
  {
    id: 35,
    name: "Holly Paula",
    description: "Business Systems Development Analyst",
    email: "hpaulay@meetup.com",
    address: "Suite 53",
    phone: "806-811-8512",
  },
  {
    id: 36,
    name: "Arlina Clemenzi",
    description: "Software Engineer I",
    email: "aclemenziz@sun.com",
    address: "Apt 402",
    phone: "586-753-1675",
  },
];

export const getCustomers = () => {
  return customers;
};

export const getOneCustomer = (id) => {
  const customer = customers.find((c) => c.id === Number(id));
  console.log(customer)
  return customer;
};
