const customers = [
  {
    id: 1,
    name: "Demetrius Blaasch",
    job: "Sales Associate",
    email: "dblaasch0@yahoo.com",
    address: "31184 Reindahl Plaza",
    phone: "211-501-0568",
  },
  {
    id: 2,
    name: "Benni Kegg",
    job: "Account Representative IV",
    email: "bkegg1@cafepress.com",
    address: "9 Pearson Junction",
    phone: "258-858-6312",
  },
  {
    id: 3,
    name: "Ulysses Auger",
    job: "Computer Systems Analyst I",
    email: "uauger2@oaic.gov.au",
    address: "393 Vahlen Park",
    phone: "610-186-8604",
  },
  {
    id: 4,
    name: "Haleigh Sawood",
    job: "Financial Analyst",
    email: "hsawood3@livejournal.com",
    address: "08441 Jenifer Crossing",
    phone: "329-198-9803",
  },
  {
    id: 5,
    name: "Odille Niemetz",
    job: "Media Manager III",
    email: "oniemetz4@theguardian.com",
    address: "00752 Luster Way",
    phone: "724-566-4836",
  },
  {
    id: 6,
    name: "Rob Iiannoni",
    job: "Legal Assistant",
    email: "riiannoni5@yolasite.com",
    address: "0378 Arizona Street",
    phone: "672-131-8664",
  },
  {
    id: 7,
    name: "Carleton Heaseman",
    job: "Mechanical Systems Engineer",
    email: "cheaseman6@trellian.com",
    address: "08302 Meadow Valley Street",
    phone: "632-470-9737",
  },
  {
    id: 8,
    name: "Ray Caspell",
    job: "Assistant Manager",
    email: "rcaspell7@redcross.org",
    address: "4 Brentwood Plaza",
    phone: "815-980-9258",
  },
  {
    id: 9,
    name: "Carmencita FitzAlan",
    job: "Programmer Analyst III",
    email: "cfitzalan8@mlb.com",
    address: "13811 Schurz Terrace",
    phone: "816-547-0450",
  },
  {
    id: 10,
    name: "Donia Jinda",
    job: "Director of Sales",
    email: "djinda9@cam.ac.uk",
    address: "389 Sachtjen Center",
    phone: "969-934-7914",
  },
  {
    id: 11,
    name: "Arri Guidelli",
    job: "Nuclear Power Engineer",
    email: "aguidellia@amazon.com",
    address: "00848 Stuart Center",
    phone: "874-393-1285",
  },
  {
    id: 12,
    name: "Patsy Casine",
    job: "Data Coordinator",
    email: "pcasineb@gnu.org",
    address: "38491 Crescent Oaks Park",
    phone: "758-763-4539",
  },
  {
    id: 13,
    name: "Sheba Grabiec",
    job: "Developer III",
    email: "sgrabiecc@bloglines.com",
    address: "512 Carioca Point",
    phone: "385-915-8446",
  },
  {
    id: 14,
    name: "Sterling Lorain",
    job: "Safety Technician IV",
    email: "sloraind@icq.com",
    address: "1 John Wall Street",
    phone: "444-741-0332",
  },
  {
    id: 15,
    name: "Eleonore Sink",
    job: "Nurse Practicioner",
    email: "esinke@tiny.cc",
    address: "1544 Browning Crossing",
    phone: "329-127-4490",
  },
  {
    id: 16,
    name: "Raviv Uttridge",
    job: "Media Manager II",
    email: "ruttridgef@yellowbook.com",
    address: "0177 Superior Plaza",
    phone: "469-772-9636",
  },
  {
    id: 17,
    name: "Morna Train",
    job: "Professor",
    email: "mtraing@bizjournals.com",
    address: "0776 5th Plaza",
    phone: "636-103-3610",
  },
  {
    id: 18,
    name: "Barclay Keitley",
    job: "Librarian",
    email: "bkeitleyh@prlog.org",
    address: "01 Westend Point",
    phone: "506-336-5907",
  },
  {
    id: 19,
    name: "Cindi Clemmensen",
    job: "Editor",
    email: "cclemmenseni@google.es",
    address: "3 Canary Parkway",
    phone: "804-404-4272",
  },
  {
    id: 20,
    name: "Melodie MacKeeg",
    job: "Teacher",
    email: "mmackeegj@zimbio.com",
    address: "41920 Manufacturers Pass",
    phone: "833-313-9782",
  },
  {
    id: 21,
    name: "Roarke Edmund",
    job: "Web Designer I",
    email: "redmundk@economist.com",
    address: "65315 Elgar Crossing",
    phone: "493-622-0801",
  },
  {
    id: 22,
    name: "Trevor Caven",
    job: "Food Chemist",
    email: "tcavenl@unicef.org",
    address: "83702 Gale Center",
    phone: "106-593-2968",
  },
  {
    id: 23,
    name: "Justinian Avard",
    job: "Database Administrator II",
    email: "javardm@patch.com",
    address: "9 Scofield Lane",
    phone: "705-280-1766",
  },
  {
    id: 24,
    name: "Maxwell Meltetal",
    job: "Operator",
    email: "mmeltetaln@cnet.com",
    address: "699 Grasskamp Center",
    phone: "967-116-1618",
  },
  {
    id: 25,
    name: "Hirsch Lewsam",
    job: "Payment Adjustment Coordinator",
    email: "hlewsamo@dmoz.org",
    address: "47 Veith Lane",
    phone: "512-763-7917",
  },
  {
    id: 26,
    name: "Karry Cheers",
    job: "Biostatistician IV",
    email: "kcheersp@ameblo.jp",
    address: "21272 Forest Dale Circle",
    phone: "917-296-1265",
  },
  {
    id: 27,
    name: "Ara Tomley",
    job: "Research Nurse",
    email: "atomleyq@intel.com",
    address: "23465 Welch Court",
    phone: "517-399-3271",
  },
  {
    id: 28,
    name: "Fred Lawlan",
    job: "Cost Accountant",
    email: "flawlanr@mtv.com",
    address: "5470 Kensington Park",
    phone: "204-111-0878",
  },
  {
    id: 29,
    name: "Inesita Forsey",
    job: "Professor",
    email: "iforseys@live.com",
    address: "19183 Oriole Point",
    phone: "400-661-4340",
  },
  {
    id: 30,
    name: "Colene Lacroix",
    job: "VP Product Management",
    email: "clacroixt@sciencedaily.com",
    address: "9790 Westerfield Terrace",
    phone: "713-249-4573",
  },
  {
    id: 31,
    name: "Garvy Surgey",
    job: "Biostatistician III",
    email: "gsurgeyu@japanpost.jp",
    address: "5463 Londonderry Center",
    phone: "165-978-6921",
  },
  {
    id: 32,
    name: "Charita Methringham",
    job: "Financial Analyst",
    email: "cmethringhamv@studiopress.com",
    address: "7 Harper Trail",
    phone: "851-646-7338",
  },
  {
    id: 33,
    name: "Baudoin Barrowclough",
    job: "Senior Financial Analyst",
    email: "bbarrowcloughw@hatena.ne.jp",
    address: "23 Tennyson Street",
    phone: "325-187-2637",
  },
  {
    id: 34,
    name: "Edgar Kaser",
    job: "Media Manager III",
    email: "ekaserx@smh.com.au",
    address: "049 Fieldstone Point",
    phone: "263-971-6042",
  },
  {
    id: 35,
    name: "Dario Grain",
    job: "Junior Executive",
    email: "dgrainy@istockphoto.com",
    address: "579 Corscot Plaza",
    phone: "847-822-8336",
  },
  {
    id: 36,
    name: "Madelin Mucillo",
    job: "Engineer I",
    email: "mmucilloz@dropbox.com",
    address: "18118 Hudson Junction",
    phone: "283-529-4017",
  },
];

export const getCustomers = () => {
  return customers;
};

export const getOneCustomer = (id) => {
  const customer = customers.find((c) => c.id === Number(id));
  console.log(customer);
  return customer;
};
