const expenses = [
  {
    id: 1,
    category: "Haier V2000",
    paymentMethod: "diners-club-enroute",
    amount: 1062,
    date: "2/10/2025",
    description: "Cataract NOS",
  },
  {
    id: 2,
    category: "Ulefone Armor 3W",
    paymentMethod: "switch",
    amount: 532,
    date: "5/17/2025",
    description: "Epil par cont w/o int ep",
  },
  { 
    id: 3,
    category: "Motorola MotoGO EX430",
    paymentMethod: "maestro",
    amount: 1742,
    date: "3/1/2025",
    description: "Periostitis-l/leg",
  },
  {
    id: 4,
    category: "alcatel OT-997D",
    paymentMethod: "maestro",
    amount: 1894,
    date: "3/23/2025",
    description: "Hodgkins sarcoma inguin",
  },
  {
    id: 5,
    category: "Huawei Mate 40",
    paymentMethod: "jcb",
    amount: 436,
    date: "4/30/2025",
    description: "Intracerebral hemorrhage",
  },
  {
    id: 6,
    category: "ZTE Blade Q Pro",
    paymentMethod: "switch",
    amount: 1313,
    date: "5/1/2025",
    description: "Hmplg mgr wo ntrc wo st",
  },
  {
    id: 7,
    category: "Spice Mi-725 Stellar Slatepad",
    paymentMethod: "mastercard",
    amount: 1031,
    date: "9/13/2024",
    description: "Twin gest-dich/diamniotc",
  },
  {
    id: 8,
    category: "LG KP502 Cookie",
    paymentMethod: "bankcard",
    amount: 1797,
    date: "3/11/2025",
    description: "Loc osteoar NOS-site NEC",
  },
  {
    id: 9,
    category: "BlackBerry Porsche Design P'9983",
    paymentMethod: "jcb",
    amount: 1086,
    date: "6/30/2025",
    description: "Late eff complic trauma",
  },
  {
    id: 10,
    category: "Lava X28 Plus",
    paymentMethod: "diners-club-international",
    amount: 1744,
    date: "9/23/2024",
    description: "Pap smear vagina w HGSIL",
  },
  {
    id: 11,
    category: "Bird S799",
    paymentMethod: "jcb",
    amount: 1978,
    date: "12/24/2024",
    description: "Benign mamm dysplas NOS",
  },
  {
    id: 12,
    category: "Samsung Convoy 2",
    paymentMethod: "switch",
    amount: 1511,
    date: "2/24/2025",
    description: "Retractile testis",
  },
  {
    id: 13,
    category: "Samsung C3050 Stratus",
    paymentMethod: "switch",
    amount: 549,
    date: "6/24/2025",
    description: "Liver injury NEC-closed",
  },
  {
    id: 14,
    category: "Samsung F520",
    paymentMethod: "diners-club-enroute",
    amount: 1336,
    date: "4/3/2025",
    description: "Carbuncle of hand",
  },
  {
    id: 15,
    category: "Samsung Galaxy S Duos 3",
    paymentMethod: "maestro",
    amount: 610,
    date: "3/4/2025",
    description: "Opn skul fx NEC-brf coma",
  },
  {
    id: 16,
    category: "Samsung Galaxy A7",
    paymentMethod: "mastercard",
    amount: 504,
    date: "8/1/2025",
    description: "Acc pois-solid/liq NOS",
  },
  {
    id: 17,
    category: "Motorola XT800 ZHISHANG",
    paymentMethod: "jcb",
    amount: 593,
    date: "5/11/2025",
    description: "TB of bronchus-no exam",
  },
  {
    id: 18,
    category: "Samsung T401G",
    paymentMethod: "diners-club-enroute",
    amount: 980,
    date: "2/28/2025",
    description: "Reye's syndrome",
  },
  {
    id: 19,
    category: "Panasonic T21",
    paymentMethod: "switch",
    amount: 1041,
    date: "9/12/2024",
    description: "Benign neo spinal cord",
  },
  {
    id: 20,
    category: "Xiaomi Redmi 10X 5G",
    paymentMethod: "jcb",
    amount: 1220,
    date: "12/22/2024",
    description: "Malignant neo larynx NOS",
  },
  {
    id: 21,
    category: "Motorola RAZR V3xx",
    paymentMethod: "switch",
    amount: 860,
    date: "7/16/2025",
    description: "Roseola infant d/t HHV-6",
  },
  {
    id: 22,
    category: "Celkon Q455L",
    paymentMethod: "jcb",
    amount: 1641,
    date: "6/19/2025",
    description: "Screen-bronch/emphysema",
  },
  {
    id: 23,
    category: "alcatel Fierce XL (Windows)",
    paymentMethod: "jcb",
    amount: 1908,
    date: "1/26/2025",
    description: "Malignant neo glottis",
  },
  {
    id: 24,
    category: "Samsung E1225 Dual Sim Shift",
    paymentMethod: "switch",
    amount: 1086,
    date: "8/7/2025",
    description: "Ch emblsm subclav veins",
  },
  {
    id: 25,
    category: "LG S365",
    paymentMethod: "jcb",
    amount: 1845,
    date: "12/9/2024",
    description: "Hodg lymph-histio pelvic",
  },
  {
    id: 26,
    category: "Samsung S3550 Shark 3",
    paymentMethod: "diners-club-enroute",
    amount: 1281,
    date: "5/8/2025",
    description: "Foreign body finger",
  },
  {
    id: 27,
    category: "Samsung Z100",
    paymentMethod: "diners-club-carte-blanche",
    amount: 1363,
    date: "12/20/2024",
    description: "Antepart malpres aff NB",
  },
  {
    id: 28,
    category: "Samsung S5600v Blade",
    paymentMethod: "switch",
    amount: 655,
    date: "4/27/2025",
    description: "Stress fx tibia/fibula",
  },
  {
    id: 29,
    category: "Telit t210",
    paymentMethod: "china-unionpay",
    amount: 846,
    date: "9/6/2024",
    description: "Injury-jump fm residence",
  },
  {
    id: 30,
    category: "Sagem MC 825 FM",
    paymentMethod: "jcb",
    amount: 1734,
    date: "11/29/2024",
    description: "Mal neo rectosigmoid jct",
  },
  {
    id: 31,
    category: "Samsung I6220 Star TV",
    paymentMethod: "mastercard",
    amount: 321,
    date: "8/26/2025",
    description: "Cl skl w oth fx-mod coma",
  },
  {
    id: 32,
    category: "Meizu M6s",
    paymentMethod: "jcb",
    amount: 1972,
    date: "3/24/2025",
    description: "Hx-allergy NEC",
  },
  {
    id: 33,
    category: "Karbonn A2+",
    paymentMethod: "switch",
    amount: 1100,
    date: "10/24/2024",
    description: "Swelling or mass of eye",
  },
  {
    id: 34,
    category: "BlackBerry Torch 9850",
    paymentMethod: "diners-club-carte-blanche",
    amount: 457,
    date: "2/15/2025",
    description: "Ant cornea pigmentation",
  },
  {
    id: 35,
    category: "Innostream INNO 89",
    paymentMethod: "americanexpress",
    amount: 427,
    date: "7/28/2025",
    description: "Liver hematoma/contusion",
  },
  {
    id: 36,
    category: "O2 XDA Zinc",
    paymentMethod: "jcb",
    amount: 427,
    date: "4/11/2025",
    description: "Recur dislocat-unspec",
  },
  {
    id: 37,
    category: "BLU Studio Touch",
    paymentMethod: "instapayment",
    amount: 1712,
    date: "11/16/2024",
    description: "Duodenum injury-closed",
  },
  {
    id: 38,
    category: "Sony Xperia C5 Ultra Dual",
    paymentMethod: "diners-club-carte-blanche",
    amount: 310,
    date: "2/9/2025",
    description: "Paratyphoid fever a",
  },
  {
    id: 39,
    category: "Sony Xperia Z3v",
    paymentMethod: "jcb",
    amount: 911,
    date: "8/19/2025",
    description: "Asy bacteruria-del w p/p",
  },
  {
    id: 40,
    category: "alcatel OT-800 One Touch CHROME",
    paymentMethod: "jcb",
    amount: 758,
    date: "12/24/2024",
    description: "Mononeuritis multiplex",
  },
  {
    id: 41,
    category: "Micromax Canvas Selfie 3 Q348",
    paymentMethod: "china-unionpay",
    amount: 497,
    date: "9/8/2024",
    description: "Toxic eff nitrogen oxide",
  },
  {
    id: 42,
    category: "Plum Optimax 11",
    paymentMethod: "visa-electron",
    amount: 939,
    date: "8/10/2025",
    description: "Chronic tonsillitis",
  },
  {
    id: 43,
    category: "Amoi A10",
    paymentMethod: "mastercard",
    amount: 1530,
    date: "9/29/2024",
    description: "Mechanical ptosis",
  },
  {
    id: 44,
    category: "OnePlus 7",
    paymentMethod: "solo",
    amount: 1158,
    date: "12/9/2024",
    description: "Erythema multiforme maj",
  },
  {
    id: 45,
    category: "alcatel OT-802 Wave",
    paymentMethod: "bankcard",
    amount: 781,
    date: "3/28/2025",
    description: "Precipitate del aff NB",
  },
  {
    id: 46,
    category: "ZTE N910",
    paymentMethod: "jcb",
    amount: 493,
    date: "9/26/2024",
    description: "Wtrcraft fall NEC-pasngr",
  },
  {
    id: 47,
    category: "Samsung Galaxy A10s",
    paymentMethod: "jcb",
    amount: 369,
    date: "11/16/2024",
    description: "Chorioamnionitis aff NB",
  },
  {
    id: 48,
    category: "Motorola E360",
    paymentMethod: "jcb",
    amount: 1374,
    date: "2/14/2025",
    description: "Radiation scoliosis",
  },
  {
    id: 49,
    category: "Huawei T158",
    paymentMethod: "jcb",
    amount: 1618,
    date: "3/13/2025",
    description: "Lt-for-dates 1500-1749g",
  },
  {
    id: 50,
    category: "Oppo Reno3 Pro 5G",
    paymentMethod: "jcb",
    amount: 1559,
    date: "1/28/2025",
    description: "Zoonotic bact dis NEC",
  },
];

export const getExpenses = () => {
  return expenses;
};