const expenses = [
  {
    id: 1,
    category: "Rent",
    paymentMethod: "Card",
    amount: 1508,
    date: "5/7/2025",
    description: "Unspecified Eustachian salpingitis",
  },
  {
    id: 2,
    category: "Marketing",
    paymentMethod: "Card",
    amount: 1184,
    date: "12/8/2024",
    description: "Unsp inj blood vessels at lower leg level, left leg, subs",
  },
  {
    id: 3,
    category: "Salaries",
    paymentMethod: "Card",
    amount: 1614,
    date: "10/2/2024",
    description: "Nondisp seg fx shaft of ulna, unsp arm, 7thQ",
  },
  {
    id: 4,
    category: "Salaries",
    paymentMethod: "Bank",
    amount: 1699,
    date: "7/30/2025",
    description: "Stable burst fx first cervcal vert, subs for fx w nonunion",
  },
  {
    id: 5,
    category: "Salaries",
    paymentMethod: "Bank",
    amount: 1959,
    date: "5/28/2025",
    description: "Capsular contracture of breast implant, subsequent encounter",
  },
  {
    id: 6,
    category: "Utilities",
    paymentMethod: "Cash",
    amount: 497,
    date: "10/22/2024",
    description: "Inj extn musc/fasc/tend l mid finger at wrs/hnd lv, sequela",
  },
  {
    id: 7,
    category: "Salaries",
    paymentMethod: "Card",
    amount: 554,
    date: "9/14/2024",
    description: "Nondisp oblique fx shaft of unsp femr, 7thK",
  },
  {
    id: 8,
    category: "Marketing",
    paymentMethod: "Cash",
    amount: 1432,
    date: "12/21/2024",
    description: "Chronic postrheumatic arthropathy [Jaccoud], left hip",
  },
  {
    id: 9,
    category: "Rent",
    paymentMethod: "Cash",
    amount: 1741,
    date: "3/6/2025",
    description: "Pnctr w/o fb of left lesser toe(s) w damage to nail",
  },
  {
    id: 10,
    category: "Supplies",
    paymentMethod: "Bank",
    amount: 1007,
    date: "2/8/2025",
    description: "Inj r int crtd, intcr w LOC w death d/t brain inj bf consc",
  },
  {
    id: 11,
    category: "Salaries",
    paymentMethod: "Card",
    amount: 1077,
    date: "12/18/2024",
    description: "Underdosing of barbiturates, sequela",
  },
  {
    id: 12,
    category: "Rent",
    paymentMethod: "Cash",
    amount: 1096,
    date: "7/25/2025",
    description: "Oth physl fx low end rad, right arm, subs for fx w malunion",
  },
  {
    id: 13,
    category: "Rent",
    paymentMethod: "Cash",
    amount: 1851,
    date: "12/28/2024",
    description: "Traumatic compartment syndrome of left lower extremity",
  },
  {
    id: 14,
    category: "Marketing",
    paymentMethod: "Cash",
    amount: 478,
    date: "8/31/2024",
    description: "Liver transplant infection",
  },
  {
    id: 15,
    category: "Supplies",
    paymentMethod: "Cash",
    amount: 1466,
    date: "12/8/2024",
    description: "Primary insomnia",
  },
  {
    id: 16,
    category: "Salaries",
    paymentMethod: "Bank",
    amount: 1555,
    date: "5/13/2025",
    description: "Animal-rider injured in other transport accident",
  },
  {
    id: 17,
    category: "Marketing",
    paymentMethod: "Cash",
    amount: 282,
    date: "4/1/2025",
    description: "Legal intervnt involving unsp firearm disch, suspect injured",
  },
  {
    id: 18,
    category: "Marketing",
    paymentMethod: "Bank",
    amount: 1656,
    date: "11/8/2024",
    description: "Spontaneous rupture of flexor tendons, left ankle and foot",
  },
  {
    id: 19,
    category: "Marketing",
    paymentMethod: "Card",
    amount: 1642,
    date: "2/17/2025",
    description: "Prolapse and hernia of ovary and fallop, unspecified side",
  },
  {
    id: 20,
    category: "Marketing",
    paymentMethod: "Card",
    amount: 1929,
    date: "12/4/2024",
    description: "Fall into natrl body of water strk surfc cause oth inj, subs",
  },
  {
    id: 21,
    category: "Supplies",
    paymentMethod: "Bank",
    amount: 1813,
    date: "12/4/2024",
    description: "Open bite of abd wall, right upper q w penet perit cav, subs",
  },
  {
    id: 22,
    category: "Rent",
    paymentMethod: "Cash",
    amount: 941,
    date: "7/16/2025",
    description: "Child psychological abuse, suspected, subsequent encounter",
  },
  {
    id: 23,
    category: "Supplies",
    paymentMethod: "Bank",
    amount: 607,
    date: "3/6/2025",
    description: "Part traum amp at lev betw knee and ankl, unsp low leg, subs",
  },
  {
    id: 24,
    category: "Salaries",
    paymentMethod: "Cash",
    amount: 1127,
    date: "9/24/2024",
    description: "Erosn implnt urethral mesh to surrnd org/tiss, sequela",
  },
  {
    id: 25,
    category: "Rent",
    paymentMethod: "Card",
    amount: 978,
    date: "4/20/2025",
    description: "Nondisp transverse fx shaft of unsp rad, 7thR",
  },
  {
    id: 26,
    category: "Supplies",
    paymentMethod: "Bank",
    amount: 982,
    date: "8/3/2025",
    description: "Nondisp fx of 3rd metatarsal bone, l ft, 7thD",
  },
  {
    id: 27,
    category: "Salaries",
    paymentMethod: "Bank",
    amount: 1825,
    date: "10/24/2024",
    description: "Poisoning by oth anti-common-cold drugs, self-harm, subs",
  },
  {
    id: 28,
    category: "Salaries",
    paymentMethod: "Card",
    amount: 1894,
    date: "3/5/2025",
    description: "Spondylolysis, thoracolumbar region",
  },
  {
    id: 29,
    category: "Rent",
    paymentMethod: "Cash",
    amount: 1035,
    date: "8/18/2025",
    description: "Foreign body in vulva and vagina, sequela",
  },
  {
    id: 30,
    category: "Rent",
    paymentMethod: "Bank",
    amount: 917,
    date: "12/16/2024",
    description: "Chronic atticoantral suppurative otitis media, bilateral",
  },
  {
    id: 31,
    category: "Supplies",
    paymentMethod: "Cash",
    amount: 870,
    date: "11/17/2024",
    description: "Complete traum amp at level betw l shldr and elbow, sequela",
  },
  {
    id: 32,
    category: "Rent",
    paymentMethod: "Bank",
    amount: 806,
    date: "10/7/2024",
    description: "Fracture of unsp part of right clavicle, init for clos fx",
  },
  {
    id: 33,
    category: "Supplies",
    paymentMethod: "Card",
    amount: 702,
    date: "4/13/2025",
    description: "Nondisp trimalleol fx unsp low leg, 7thK",
  },
  {
    id: 34,
    category: "Supplies",
    paymentMethod: "Cash",
    amount: 1340,
    date: "1/14/2025",
    description: "Other paraphilias",
  },
  {
    id: 35,
    category: "Utilities",
    paymentMethod: "Cash",
    amount: 604,
    date: "3/28/2025",
    description: "Dislocation of septal cartilage of nose, subs encntr",
  },
  {
    id: 36,
    category: "Marketing",
    paymentMethod: "Card",
    amount: 871,
    date: "2/28/2025",
    description: "Drown due to being thrown ovrbrd by motion of inflatbl crft",
  },
  {
    id: 37,
    category: "Salaries",
    paymentMethod: "Cash",
    amount: 690,
    date: "4/9/2025",
    description: "War operations involving explosion of marine weapons",
  },
  {
    id: 38,
    category: "Salaries",
    paymentMethod: "Card",
    amount: 1418,
    date: "9/7/2024",
    description: "Pasngr on bus inj in clsn w nonmtr vehicle in traf, sequela",
  },
  {
    id: 39,
    category: "Rent",
    paymentMethod: "Bank",
    amount: 431,
    date: "12/20/2024",
    description: "Blister (nonthermal) of left forearm, sequela",
  },
  {
    id: 40,
    category: "Salaries",
    paymentMethod: "Cash",
    amount: 1979,
    date: "12/17/2024",
    description: "Enctr for pro mgmt and counseling for gestational carrier",
  },
  {
    id: 41,
    category: "Rent",
    paymentMethod: "Cash",
    amount: 1825,
    date: "8/1/2025",
    description: "Low-tension glaucoma, unspecified eye, moderate stage",
  },
  {
    id: 42,
    category: "Utilities",
    paymentMethod: "Bank",
    amount: 1021,
    date: "11/7/2024",
    description: "External constrict of part of breast, unsp breast, sequela",
  },
  {
    id: 43,
    category: "Salaries",
    paymentMethod: "Cash",
    amount: 1934,
    date: "2/12/2025",
    description: "Reiter's disease, left hand",
  },
  {
    id: 44,
    category: "Utilities",
    paymentMethod: "Card",
    amount: 597,
    date: "10/30/2024",
    description: "Monoplg upr lmb fol ntrm intcrbl hemor aff left dom side",
  },
  {
    id: 45,
    category: "Supplies",
    paymentMethod: "Bank",
    amount: 1713,
    date: "12/21/2024",
    description: "Oth types of non-Hodgkin lymphoma, intrapelvic lymph nodes",
  },
  {
    id: 46,
    category: "Salaries",
    paymentMethod: "Bank",
    amount: 1286,
    date: "8/7/2025",
    description: "Exposure to ignition or melting of nightwear, subs encntr",
  },
  {
    id: 47,
    category: "Supplies",
    paymentMethod: "Cash",
    amount: 1768,
    date: "5/29/2025",
    description: "Nondisp transverse fx shaft of unsp ulna, 7thD",
  },
  {
    id: 48,
    category: "Supplies",
    paymentMethod: "Card",
    amount: 507,
    date: "10/23/2024",
    description: "Unspecified physeal fracture of unspecified calcaneus, 7thK",
  },
  {
    id: 49,
    category: "Marketing",
    paymentMethod: "Cash",
    amount: 374,
    date: "11/5/2024",
    description: "Toxic effect of dichloromethane, accidental, init",
  },
  {
    id: 50,
    category: "Rent",
    paymentMethod: "Cash",
    amount: 627,
    date: "8/29/2025",
    description: "Disp fx of cuboid bone of r foot, subs for fx w routn heal",
  },
];

export const getExpenses = () => {
  return expenses;
};
