const revenues = [
  {
    id: 1,
    customerId: 23,
    amount: 851,
    source: "Food - Beverages",
    paymentMethod: "epay",
    date: "6/22/2025",
    description: "Chalazion",
    status: "complete",
  },
  {
    id: 2,
    customerId: 15,
    amount: 1919,
    source: "Food - Dried Fruits",
    paymentMethod: "cash",
    date: "9/21/2024",
    description: "Fx symphy mandib body-cl",
    status: "complete",
  },
  {
    id: 3,
    customerId: 27,
    amount: 1897,
    source: "Kitchen",
    paymentMethod: "card",
    date: "2/7/2025",
    description: "Mult endo neoplas type I",
    status: "complete",
  },
  {
    id: 4,
    customerId: 26,
    amount: 1208,
    source: "Toys",
    paymentMethod: "check",
    date: "6/13/2025",
    description: "Histoplasm capsul mening",
    status: "refunded",
  },
  {
    id: 5,
    customerId: 9,
    amount: 1071,
    source: "Garden",
    paymentMethod: "card",
    date: "10/3/2024",
    description: "Mononeuritis multiplex",
    status: "pending",
  },
  {
    id: 6,
    customerId: 3,
    amount: 154,
    source: "Food - Condiments",
    paymentMethod: "epay",
    date: "1/2/2025",
    description: "3rd deg burn foot",
    status: "refunded",
  },
  {
    id: 7,
    customerId: 32,
    amount: 978,
    source: "Food - Condiments",
    paymentMethod: "cash",
    date: "6/5/2025",
    description: "Late syphilis NOS",
    status: "pending",
  },
  {
    id: 8,
    customerId: 12,
    amount: 1855,
    source: "Food - Canned Goods",
    paymentMethod: "epay",
    date: "12/24/2024",
    description: "Urethr strict:infect NOS",
    status: "refunded",
  },
  {
    id: 9,
    customerId: 2,
    amount: 1237,
    source: "Clothing - Shirts",
    paymentMethod: "card",
    date: "11/19/2024",
    description: "Attn defic nonhyperact",
    status: "refunded",
  },
  {
    id: 10,
    customerId: 3,
    amount: 146,
    source: "Food - Frozen Foods",
    paymentMethod: "epay",
    date: "9/6/2024",
    description: "Infec otitis externa NOS",
    status: "refunded",
  },
  {
    id: 11,
    customerId: 23,
    amount: 1951,
    source: "Food - Grains",
    paymentMethod: "cash",
    date: "11/19/2024",
    description: "Fet damg d/t virus-deliv",
    status: "refunded",
  },
  {
    id: 12,
    customerId: 10,
    amount: 479,
    source: "Food - Frozen Foods",
    paymentMethod: "cash",
    date: "10/5/2024",
    description: "Personality disorder NOS",
    status: "pending",
  },
  {
    id: 13,
    customerId: 17,
    amount: 781,
    source: "Kitchen",
    paymentMethod: "card",
    date: "10/23/2024",
    description: "Fx femur NOS-open",
    status: "pending",
  },
  {
    id: 14,
    customerId: 20,
    amount: 746,
    source: "Food - Pasta",
    paymentMethod: "card",
    date: "6/22/2025",
    description: "Accidnt-mech firearm/gun",
    status: "refunded",
  },
  {
    id: 15,
    customerId: 26,
    amount: 868,
    source: "Toys",
    paymentMethod: "check",
    date: "4/7/2025",
    description: "Ab NOS w pelv damag-inc",
    status: "complete",
  },
  {
    id: 16,
    customerId: 33,
    amount: 254,
    source: "Garden",
    paymentMethod: "cash",
    date: "3/26/2025",
    description: "Opn wound elbow w tendon",
    status: "refunded",
  },
  {
    id: 17,
    customerId: 3,
    amount: 284,
    source: "Garden",
    paymentMethod: "card",
    date: "11/22/2024",
    description: "Oth spcf joint replaced",
    status: "pending",
  },
  {
    id: 18,
    customerId: 14,
    amount: 1619,
    source: "Smart Home",
    paymentMethod: "card",
    date: "4/28/2025",
    description: "Poison-gas/vapor NOS",
    status: "pending",
  },
  {
    id: 19,
    customerId: 21,
    amount: 1555,
    source: "Food - Grains",
    paymentMethod: "epay",
    date: "7/10/2025",
    description: "Fx femur shaft-closed",
    status: "refunded",
  },
  {
    id: 20,
    customerId: 21,
    amount: 1643,
    source: "Smart Home",
    paymentMethod: "check",
    date: "5/24/2025",
    description: "Stress reaction, fugue",
    status: "complete",
  },
  {
    id: 21,
    customerId: 17,
    amount: 102,
    source: "Electronics",
    paymentMethod: "check",
    date: "8/29/2025",
    description: "Persist occiptpost-deliv",
    status: "pending",
  },
  {
    id: 22,
    customerId: 2,
    amount: 560,
    source: "Food - Bakery",
    paymentMethod: "cash",
    date: "3/1/2025",
    description: "Lordosis NOS",
    status: "complete",
  },
  {
    id: 23,
    customerId: 6,
    amount: 1561,
    source: "Electronics",
    paymentMethod: "cash",
    date: "6/26/2025",
    description: "Patau's syndrome",
    status: "refunded",
  },
  {
    id: 24,
    customerId: 11,
    amount: 540,
    source: "Pets",
    paymentMethod: "cash",
    date: "10/16/2024",
    description: "Burkitt's tumor thorax",
    status: "refunded",
  },
  {
    id: 25,
    customerId: 34,
    amount: 1147,
    source: "Home",
    paymentMethod: "check",
    date: "9/21/2024",
    description: "Benign neo bone NOS",
    status: "pending",
  },
  {
    id: 26,
    customerId: 14,
    amount: 1852,
    source: "Food - Frozen Foods",
    paymentMethod: "epay",
    date: "6/24/2025",
    description: "Monplga lwr lmb unsp sde",
    status: "pending",
  },
  {
    id: 27,
    customerId: 1,
    amount: 480,
    source: "Kitchen",
    paymentMethod: "epay",
    date: "7/2/2025",
    description: "Hmplg mgrn w ntrc w st",
    status: "refunded",
  },
  {
    id: 28,
    customerId: 19,
    amount: 893,
    source: "Food - Vegetarian",
    paymentMethod: "cash",
    date: "11/24/2024",
    description: "Alcoh induce sleep disor",
    status: "pending",
  },
  {
    id: 29,
    customerId: 22,
    amount: 488,
    source: "Smart Home",
    paymentMethod: "cash",
    date: "8/31/2024",
    description: "Cardiac dysrhythmias NEC",
    status: "pending",
  },
  {
    id: 30,
    customerId: 36,
    amount: 1466,
    source: "Home",
    paymentMethod: "cash",
    date: "1/25/2025",
    description: "Giardiasis",
    status: "refunded",
  },
  {
    id: 31,
    customerId: 21,
    amount: 694,
    source: "Food - Spices",
    paymentMethod: "card",
    date: "4/3/2025",
    description: "Screen for malnutrition",
    status: "pending",
  },
  {
    id: 32,
    customerId: 7,
    amount: 1643,
    source: "Outdoor",
    paymentMethod: "check",
    date: "6/24/2025",
    description: "Hyphema",
    status: "refunded",
  },
  {
    id: 33,
    customerId: 33,
    amount: 303,
    source: "Accessories",
    paymentMethod: "epay",
    date: "9/7/2024",
    description: "H zoster complicated NOS",
    status: "complete",
  },
  {
    id: 34,
    customerId: 34,
    amount: 1794,
    source: "Food - Meats",
    paymentMethod: "card",
    date: "3/28/2025",
    description: "Ac bulbar polio-type NOS",
    status: "pending",
  },
  {
    id: 35,
    customerId: 4,
    amount: 1483,
    source: "Clothing - Tops",
    paymentMethod: "card",
    date: "11/17/2024",
    description: "Postpart coagul def-unsp",
    status: "refunded",
  },
  {
    id: 36,
    customerId: 12,
    amount: 1798,
    source: "Electronics",
    paymentMethod: "epay",
    date: "5/23/2025",
    description: "Adv eff chloramphenicol",
    status: "refunded",
  },
  {
    id: 37,
    customerId: 30,
    amount: 225,
    source: "Home",
    paymentMethod: "card",
    date: "1/1/2025",
    description: "3rd burn w loss-breast",
    status: "refunded",
  },
  {
    id: 38,
    customerId: 1,
    amount: 1436,
    source: "Food - Dressings",
    paymentMethod: "check",
    date: "12/27/2024",
    description: "Lump or mass in breast",
    status: "pending",
  },
  {
    id: 39,
    customerId: 4,
    amount: 258,
    source: "Travel",
    paymentMethod: "check",
    date: "4/28/2025",
    description: "Gastrostomy comp NEC",
    status: "complete",
  },
  {
    id: 40,
    customerId: 18,
    amount: 1446,
    source: "Food - Frozen Food",
    paymentMethod: "epay",
    date: "12/31/2024",
    description: "AMI inferopost, subseq",
    status: "refunded",
  },
  {
    id: 41,
    customerId: 4,
    amount: 1180,
    source: "Food - Canned Goods",
    paymentMethod: "check",
    date: "10/6/2024",
    description: "Oth postsurgery lordosis",
    status: "pending",
  },
  {
    id: 42,
    customerId: 11,
    amount: 1538,
    source: "Food - Meat",
    paymentMethod: "epay",
    date: "5/2/2025",
    description: "Malig neo sublingual",
    status: "complete",
  },
  {
    id: 43,
    customerId: 36,
    amount: 267,
    source: "Food - Soups",
    paymentMethod: "epay",
    date: "10/2/2024",
    description: "Reg enteritis, lg intest",
    status: "complete",
  },
  {
    id: 44,
    customerId: 9,
    amount: 1187,
    source: "Clothing - Footwear",
    paymentMethod: "check",
    date: "5/10/2025",
    description: "Varic vein leg-antepart",
    status: "pending",
  },
  {
    id: 45,
    customerId: 13,
    amount: 897,
    source: "Food - Beverages",
    paymentMethod: "cash",
    date: "7/14/2025",
    description: "Opn skl base fx-coma NOS",
    status: "complete",
  },
  {
    id: 46,
    customerId: 16,
    amount: 797,
    source: "Food - Nuts",
    paymentMethod: "card",
    date: "4/28/2025",
    description: "Hx traumatc brain injury",
    status: "refunded",
  },
  {
    id: 47,
    customerId: 1,
    amount: 1424,
    source: "Home Appliances",
    paymentMethod: "cash",
    date: "11/6/2024",
    description: "Open wnd forehead-compl",
    status: "pending",
  },
  {
    id: 48,
    customerId: 30,
    amount: 1832,
    source: "Food - Meat",
    paymentMethod: "cash",
    date: "4/22/2025",
    description: "Leg ab w metab dis-unsp",
    status: "pending",
  },
  {
    id: 49,
    customerId: 18,
    amount: 782,
    source: "Food - Meat Substitutes",
    paymentMethod: "epay",
    date: "1/12/2025",
    description: "T7-t12 spin cord inj NOS",
    status: "complete",
  },
  {
    id: 50,
    customerId: 6,
    amount: 575,
    source: "Food - Frozen Foods",
    paymentMethod: "epay",
    date: "2/22/2025",
    description: "Chronic skin ulcer NOS",
    status: "pending",
  },
  {
    id: 51,
    customerId: 1,
    amount: 1274,
    source: "Electronics",
    paymentMethod: "epay",
    date: "12/23/2024",
    description: "Pneumonia d/t chlamydia",
    status: "pending",
  },
  {
    id: 52,
    customerId: 17,
    amount: 394,
    source: "Kitchen",
    paymentMethod: "cash",
    date: "6/24/2025",
    description: "Palindrom rheum-l/leg",
    status: "pending",
  },
  {
    id: 53,
    customerId: 30,
    amount: 1563,
    source: "Food - Dried Fruits",
    paymentMethod: "card",
    date: "2/19/2025",
    description: "Spirochetal infect NOS",
    status: "pending",
  },
  {
    id: 54,
    customerId: 12,
    amount: 1590,
    source: "Kitchen",
    paymentMethod: "epay",
    date: "4/23/2025",
    description: "Ankylosis-lower/leg",
    status: "pending",
  },
  {
    id: 55,
    customerId: 16,
    amount: 995,
    source: "Tools",
    paymentMethod: "check",
    date: "9/16/2024",
    description: "Congen bronchiectasis",
    status: "complete",
  },
  {
    id: 56,
    customerId: 16,
    amount: 296,
    source: "Health",
    paymentMethod: "cash",
    date: "12/22/2024",
    description: "Deep 3rd deg burn thigh",
    status: "complete",
  },
  {
    id: 57,
    customerId: 11,
    amount: 1779,
    source: "Food - Meat & Seafood",
    paymentMethod: "epay",
    date: "9/25/2024",
    description: "Suppr lactation-postpart",
    status: "complete",
  },
  {
    id: 58,
    customerId: 19,
    amount: 936,
    source: "Food - Breakfast",
    paymentMethod: "check",
    date: "1/6/2025",
    description: "Adv eff butyrophen tranq",
    status: "pending",
  },
  {
    id: 59,
    customerId: 26,
    amount: 1808,
    source: "Food - Spices",
    paymentMethod: "cash",
    date: "11/5/2024",
    description: "Inj superior mesent vein",
    status: "refunded",
  },
  {
    id: 60,
    customerId: 10,
    amount: 1768,
    source: "Kitchen",
    paymentMethod: "card",
    date: "4/2/2025",
    description: "Mal neo stomach body",
    status: "pending",
  },
  {
    id: 61,
    customerId: 18,
    amount: 1163,
    source: "Food - Produce",
    paymentMethod: "epay",
    date: "7/30/2025",
    description: "Ac epiglottitis w obstr",
    status: "pending",
  },
  {
    id: 62,
    customerId: 34,
    amount: 1460,
    source: "Home",
    paymentMethod: "epay",
    date: "5/21/2025",
    description: "Sprain of ankle deltoid",
    status: "pending",
  },
  {
    id: 63,
    customerId: 21,
    amount: 1582,
    source: "Health",
    paymentMethod: "check",
    date: "3/27/2025",
    description: "Malaria-delivered",
    status: "complete",
  },
  {
    id: 64,
    customerId: 3,
    amount: 1615,
    source: "Food - Breakfast",
    paymentMethod: "epay",
    date: "12/12/2024",
    description: "Loose body in knee",
    status: "pending",
  },
  {
    id: 65,
    customerId: 4,
    amount: 152,
    source: "Home",
    paymentMethod: "cash",
    date: "12/23/2024",
    description: "Periapical abscess",
    status: "pending",
  },
  {
    id: 66,
    customerId: 24,
    amount: 720,
    source: "Outdoor",
    paymentMethod: "cash",
    date: "1/11/2025",
    description: "Salivary gland absence",
    status: "pending",
  },
  {
    id: 67,
    customerId: 17,
    amount: 827,
    source: "Pets",
    paymentMethod: "cash",
    date: "11/1/2024",
    description: "Sev nonprolf db retinoph",
    status: "complete",
  },
  {
    id: 68,
    customerId: 5,
    amount: 959,
    source: "Pets",
    paymentMethod: "card",
    date: "2/5/2025",
    description: "Fall from cliff",
    status: "refunded",
  },
  {
    id: 69,
    customerId: 13,
    amount: 1020,
    source: "Food - Bakery",
    paymentMethod: "epay",
    date: "11/30/2024",
    description: "Trichuriasis",
    status: "pending",
  },
  {
    id: 70,
    customerId: 19,
    amount: 150,
    source: "Art Supplies",
    paymentMethod: "cash",
    date: "10/18/2024",
    description: "Hydatidiform mole",
    status: "pending",
  },
  {
    id: 71,
    customerId: 4,
    amount: 1683,
    source: "Kitchen",
    paymentMethod: "check",
    date: "8/4/2025",
    description: "Aneurysm NEC",
    status: "pending",
  },
  {
    id: 72,
    customerId: 12,
    amount: 1653,
    source: "Audio",
    paymentMethod: "card",
    date: "5/23/2025",
    description: "Histoplasm dub endocard",
    status: "refunded",
  },
  {
    id: 73,
    customerId: 36,
    amount: 398,
    source: "Food - Desserts",
    paymentMethod: "cash",
    date: "6/28/2025",
    description: "TB brain absc-micro dx",
    status: "refunded",
  },
  {
    id: 74,
    customerId: 10,
    amount: 1097,
    source: "Office",
    paymentMethod: "cash",
    date: "2/25/2025",
    description: "Interrupt of aortic arch",
    status: "complete",
  },
  {
    id: 75,
    customerId: 17,
    amount: 1023,
    source: "Food - Spices",
    paymentMethod: "check",
    date: "5/22/2025",
    description: "Ulcerative proctitis",
    status: "complete",
  },
  {
    id: 76,
    customerId: 10,
    amount: 113,
    source: "Clothing - Jumpsuits",
    paymentMethod: "cash",
    date: "11/5/2024",
    description: "Circadian rhythm-jetlag",
    status: "refunded",
  },
  {
    id: 77,
    customerId: 20,
    amount: 1578,
    source: "Food - Produce",
    paymentMethod: "cash",
    date: "10/6/2024",
    description: "Oth rd veh acc-pers NOS",
    status: "complete",
  },
  {
    id: 78,
    customerId: 8,
    amount: 1696,
    source: "Accessories",
    paymentMethod: "check",
    date: "12/23/2024",
    description: "Chr erythrm w/o ach rmsn",
    status: "complete",
  },
  {
    id: 79,
    customerId: 1,
    amount: 1930,
    source: "Clothing - Accessories",
    paymentMethod: "check",
    date: "9/27/2024",
    description: "Chr gingivitis-nonplaque",
    status: "pending",
  },
  {
    id: 80,
    customerId: 21,
    amount: 1285,
    source: "Food - Frozen Meals",
    paymentMethod: "card",
    date: "1/30/2025",
    description: "Cl skull vlt fx-brf coma",
    status: "complete",
  },
  {
    id: 81,
    customerId: 7,
    amount: 1228,
    source: "Smart Home",
    paymentMethod: "check",
    date: "11/11/2024",
    description: "Benign neo conjunctiva",
    status: "pending",
  },
  {
    id: 82,
    customerId: 4,
    amount: 1493,
    source: "Food - Frozen Foods",
    paymentMethod: "epay",
    date: "4/5/2025",
    description: "Diabetes-postpartum",
    status: "refunded",
  },
  {
    id: 83,
    customerId: 13,
    amount: 568,
    source: "Clothing",
    paymentMethod: "cash",
    date: "9/26/2024",
    description: "Opn skl fx NEC-deep coma",
    status: "refunded",
  },
  {
    id: 84,
    customerId: 27,
    amount: 1971,
    source: "Automotive",
    paymentMethod: "cash",
    date: "4/22/2025",
    description: "Keratitis NOS",
    status: "complete",
  },
  {
    id: 85,
    customerId: 30,
    amount: 471,
    source: "Clothing",
    paymentMethod: "check",
    date: "8/14/2025",
    description: "Abo incompat react NOS",
    status: "complete",
  },
  {
    id: 86,
    customerId: 5,
    amount: 579,
    source: "Toys",
    paymentMethod: "check",
    date: "4/19/2025",
    description: "2nd deg burn hand-mult",
    status: "pending",
  },
  {
    id: 87,
    customerId: 17,
    amount: 1308,
    source: "Footwear",
    paymentMethod: "card",
    date: "10/16/2024",
    description: "Ch emblsm up ext NOS",
    status: "pending",
  },
  {
    id: 88,
    customerId: 12,
    amount: 1430,
    source: "Safety",
    paymentMethod: "cash",
    date: "12/14/2024",
    description: "TB peritonitis-oth test",
    status: "refunded",
  },
  {
    id: 89,
    customerId: 6,
    amount: 1606,
    source: "Home Appliances",
    paymentMethod: "card",
    date: "6/1/2025",
    description: "Fall-occ unpower aircraf",
    status: "refunded",
  },
  {
    id: 90,
    customerId: 2,
    amount: 916,
    source: "Food - Salads",
    paymentMethod: "epay",
    date: "5/16/2025",
    description: "Overflow incontinence",
    status: "refunded",
  },
  {
    id: 91,
    customerId: 23,
    amount: 1723,
    source: "Art Supplies",
    paymentMethod: "check",
    date: "1/9/2025",
    description: "Loc prim osteoarth-hand",
    status: "complete",
  },
  {
    id: 92,
    customerId: 36,
    amount: 300,
    source: "Electronics",
    paymentMethod: "check",
    date: "5/24/2025",
    description: "Tension headache NOS",
    status: "refunded",
  },
  {
    id: 93,
    customerId: 4,
    amount: 1565,
    source: "Food - Spices",
    paymentMethod: "cash",
    date: "11/14/2024",
    description: "Extradural hem-mod coma",
    status: "pending",
  },
  {
    id: 94,
    customerId: 19,
    amount: 763,
    source: "Clothing - Activewear",
    paymentMethod: "check",
    date: "2/11/2025",
    description: "Accommodative esotropia",
    status: "complete",
  },
  {
    id: 95,
    customerId: 4,
    amount: 556,
    source: "Accessories",
    paymentMethod: "cash",
    date: "10/26/2024",
    description: "Joint effusion-mult jts",
    status: "refunded",
  },
  {
    id: 96,
    customerId: 16,
    amount: 938,
    source: "Food - Seafood",
    paymentMethod: "card",
    date: "10/6/2024",
    description: "Aircraf acc-occ comm NEC",
    status: "refunded",
  },
  {
    id: 97,
    customerId: 24,
    amount: 319,
    source: "Food - Desserts",
    paymentMethod: "check",
    date: "5/11/2025",
    description: "Cerebel lacer-concussion",
    status: "refunded",
  },
  {
    id: 98,
    customerId: 33,
    amount: 214,
    source: "Food - Produce",
    paymentMethod: "card",
    date: "6/6/2025",
    description: "Submers NEC-person NEC",
    status: "pending",
  },
  {
    id: 99,
    customerId: 15,
    amount: 986,
    source: "Storage",
    paymentMethod: "check",
    date: "8/3/2025",
    description: "Exfl d/t eryth 80-89 bdy",
    status: "pending",
  },
  {
    id: 100,
    customerId: 30,
    amount: 1987,
    source: "Pets",
    paymentMethod: "card",
    date: "11/20/2024",
    description: "Organic writers' cramp",
    status: "complete",
  },
];

export const getRevenues = () => {
  return revenues;
};
